### ISSUE TITLE
Modifying FramerateTime-Stretches Rendered Videos

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#94]
**Describe the bug**
Modifying framerate time-stretches rendered videos

**To Reproduce**
1. Go to the Settings menu and change your framerate to something other than 60 fps
2. Render a midi to video
3. The rendered video will play at 60 fps, and recorded frames will be time-stretched to match

**Expected behavior**
Rendered videos should play back at the selected frame rate

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 18362.719
 - Version 1.0.4

**Additional context**
Other effects, such as Gamer Mode (now disabled in renders,) play back in real time during renders, and are therefore sped up in the final output.

**Comment by LyricWulf** [comment]
At the moment, only 60fps output is available (iirc I put, please use 60fps in the tooltip).

This is for practical reasons, as there are few reasons to have other framerates at this time.

30fps is not smooth and does not decrease render times by a lot.
120/240 fps are not supported by any online video platform.

I may resolve this by forcing the framerate to be 60fps in the future.

**Comment by Naturalizze** [comment]
To explain in further detail: 

The rendering times might take a bit longer to do at 1080p60, but all that does is give viewers more options and opportunities to view the video. If uploaded to YouTube or Vimeo in 1080p60, they give you an option to watch in 720p60 or 480p30. The file sizes *after* using the script to convert them to .mp4 aren't large, and as long as you're not doing a TON of extra effects in post for editing and uploading, it *shouldn't* be too much of an issue. Due to these reasons, as Lyric mentioned above, this is a low priority bug.

Suggestion: if you still wanted to make the end video file be in 720p30 or a different resolution/frame rate, you can always use a different FFmpeg command, to change that, edit the FFmpeg script before running it to set those parameters, or use a software like WinFF to give you an interface to utilize FFmpeg to change it how you'd like. 

Hope this helps clear this situation up :)

**Comment by Th3Gavst3r** [comment]
I agree it's low priority, and that locking to 1080p60 is an excellent solution. 
IMO the biggest bug here is that users will be confused :)

**Comment by lyricwulf** [comment]
Framerate has been removed from the program for the time being. Feel free to re-open if similar issues happen in the future
